### PR TITLE
Add JBCNConf 2015 logo

### PR DESCRIPTION
**Pull request by szpak**

### CODE REVIEW

**Comment by bandrzejczak** [comment]
Don't forget to run the deploy script.

**Comment by mihn** [comment]
Im on it :)

On 4 April 2015 at 09:43, Bartek Andrzejczak <notifications@github.com>
wrote:

> Don't forget to run the deploy script.
>
> On Sat, Apr 4, 2015, 9:34 AM Michał Niczyporuk <notifications@github.com>
> wrote:
>
> > Merged #35 <https://github.com/warszawajug/wjug/pull/35>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/warszawajug/wjug/pull/35#event-273181768>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/warszawajug/wjug/pull/35#issuecomment-89516795>.
>



-- 
Pozdrawiam,
Michał Niczyporuk

**Comment by mihn** [comment]
http://warszawa.jug.pl/#/about look, ma! i didnt break anything! :)

**Comment by bandrzejczak** [comment]
I'm proud of ya! I'm always scared when I press Ctrl + C. I'll try to
change this sick procedure ;)

**Comment by bandrzejczak** [comment]
@mihn Here you go: #36

**Pull request merged**
